### ISSUE TITLE
[banuser] Rudimentary hands-on Reddit API test

### ISSUE THREAD

**Issue by wllrd** [citizensandtech/CivilServant#72]
- [x] Configure experiment with values from #71 
- [x] Test that the system starts/runs
- [x] Test that mod actions are read
- [x] Test that banned user is entered into the experiment
- [x] Test that intervention messages are sent

**Comment by dantaeyoung** [comment]
This works! Tested the above:

Confirmed that data was loaded into mod_actions table
Confirmed that experiment_thing was created for banned user enrolled in experiment
Confirmed that message was sent to reddit user via reddit
