### ISSUE TITLE
[banuser] Fix deployment and testing mismatch of modactions format

### ISSUE THREAD

**Issue by dantaeyoung** [citizensandtech/CivilServant#77]
In deployment, `instance.fetched_mod_actions` (as seen in line 72 of `banneduser_experiment_controller.py)` returns a `praw.models.ModAction` object and can only be referred to with attributes. (e.g. `modaction.action`)

However, our tests are written to use fixture data that offers a list of dicts (e.g. `modaction['action']`). As such, tests fail when deployment works.

On the `modaction_praw_object_bug` branch I've pushed a commit that works on the dryrun server for deployment, but fails tests.

**Comment by wllrd** [comment]
this is now addressed in changes pushed to #83
