### ISSUE TITLE
[banuser] `update_existing_participants` not being called in production?

### ISSUE THREAD

**Issue by wllrd** [citizensandtech/CivilServant#79]
TODO: investigate this issue

**Comment by dantaeyoung** [comment]
(This is when a tempbanned user is already tempbanned)

**Comment by dantaeyoung** [comment]
Note: ExperimentThing seems to be not edited upon change in ban status. We should reset the `civilservant_production` database and test this after #87 is merged.

**Comment by wllrd** [comment]
- `commit` must be called explicitly before returning
- updates should only apply to `temporary` ban types
- mod actions could/should be applied exactly once; probably need to use timestamps

**Comment by wllrd** [comment]
relevant updates were commited in the admittedly-hacky #88
