### ISSUE TITLE
[banuser] Add categories based on comment history

### ISSUE THREAD

**Issue by wllrd** [citizensandtech/CivilServant#98]
categories are:

- `lurker`: never commented 
- `lowremoval`: commented in the past 6mo and low % of comments removed in the past 6 mo
- `highremoval`: commented in the past 6mo and high % of comments removed in the past 6 mo

these should be combined with the current categories based on ban duration.

**Comment by wllrd** [comment]
basic idea in #99

**Comment by dantaeyoung** [comment]
Categories are thus:
```
highremoval_fourteendays
highremoval_sevendays
highremoval_thirtydays
highremoval_threedays
lowremoval_fourteendays
lowremoval_sevendays
lowremoval_thirtydays
lowremoval_threedays
lurker_fourteendays
lurker_sevendays
lurker_thirtydays
lurker_threedays
```

**Comment by dantaeyoung** [comment]
We have to decide on whether comment removal history is calculated based on 'past 6 mo', or '6 mo before experiment start'. 'Past 6 months' is ideal for Lucas but may run into performance issues with querying the database.

**Comment by dantaeyoung** [comment]
Note: Have median cutoff (of comment removal %) specified as a static number in the configuration file
